name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "invalid"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. @ yourgithhubusername
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 0.1.0 (Current/Stable)
        - 0.1.0 (Dev/Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: oss
    attributes:
      label: What operating system are you on?
      multiple: true
      options:
        - Linux (Ubuntu, Fedora, RHEL, Arch)
        - Windows 10 or 11
        - MacOS
  - type: textarea
    id: logs
    attributes:
      label: Relevant code that may have caused the issue
      description: Please copy and paste any relevant Python code to help us reproducing the issue. This will be automatically formatted into code, so no need for backticks.
      render: python
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs (warnings or error messages)
      description: Please copy and paste any logs. This will be automatically
        formatted, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct.
        - label: I agree to follow this project's Code of Conduct
          required: true
